-- MySQL Script generated by MySQL Workbench
-- Thu Jun 30 22:44:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema codgamdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codgamdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codgamdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `codgamdb` ;

-- -----------------------------------------------------
-- Table `codgamdb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codgamdb`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `codgamdb`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codgamdb`.`stock` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `codgamdb`.`userType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codgamdb`.`userType` (
  `id` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `codgamdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codgamdb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(55) NOT NULL,
  `lastName` VARCHAR(55) NOT NULL,
  `dni` BIGINT NOT NULL,
  `bDate` DATE NOT NULL,
  `phone` BIGINT NOT NULL,
  `avatar` BLOB NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `password` CHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `userType` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `userType_idx` (`userType` ASC) VISIBLE,
  CONSTRAINT `userType`
    FOREIGN KEY (`userType`)
    REFERENCES `codgamdb`.`userType` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `codgamdb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codgamdb`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(55) NOT NULL,
  `img1` BLOB NULL DEFAULT NULL,
  `img2` BLOB NULL DEFAULT NULL,
  `img3` BLOB NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `price` SMALLINT NOT NULL,
  `shipping` TINYINT NOT NULL,
  `discount` TINYINT NOT NULL,
  `id_category` INT NOT NULL,
  `id_stock` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `category_idx` (`id_category` ASC, `id` ASC) VISIBLE,
  INDEX `stock_idx` (`id_stock` ASC) VISIBLE,
  INDEX `product_idx` (`id` ASC) VISIBLE,
  CONSTRAINT `category`
    FOREIGN KEY (`id_category`)
    REFERENCES `codgamdb`.`category` (`id`),
  CONSTRAINT `stock`
    FOREIGN KEY (`id_stock`)
    REFERENCES `codgamdb`.`stock` (`id`),
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
